package com.crabmod.hotbath.mixin.alexscaves;

import com.crabmod.hotbath.mixin.HotBathMixinPlugin;
import net.neoforged.fml.loading.FMLLoader;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that conditionally loads Alex's Caves mixins only when:
 * 1. The mod is present
 * 2. Compatibility mode is NOT enabled
 * 
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class AlexsCavesMixinPlugin implements IMixinConfigPlugin {
    
    private static Boolean alexsCavesLoaded = null;
    
    private static boolean checkAlexsCavesPresent() {
        if (alexsCavesLoaded == null) {
            try {
                alexsCavesLoaded = FMLLoader.getLoadingModList().getModFileById("alexscaves") != null;
                if (alexsCavesLoaded) {
                    System.out.println("[HotBath] Alex's Caves detected via FMLLoader");
                }
            } catch (Throwable t) {
                alexsCavesLoaded = false;
            }
        }
        return alexsCavesLoaded;
    }
    
    @Override
    public void onLoad(String mixinPackage) {
        checkAlexsCavesPresent();
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Disable if compatibility mode is enabled
        if (HotBathMixinPlugin.isCompatibilityModeEnabled()) {
            return false;
        }
        // Only apply mixins if Alex's Caves is loaded
        return checkAlexsCavesPresent();
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {}
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {}
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {}
}
