package com.crabmod.hotbath.mixin;

import com.crabmod.hotbath.util.HotbathFluidHelper;
import com.crabmod.hotbath.waterlogging.HotbathWaterloggingHelper;
import net.minecraft.core.BlockPos;
import net.minecraft.tags.FluidTags;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.BarrierBlock;
import net.minecraft.world.level.block.SimpleWaterloggedBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.FlowingFluid;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.level.material.Fluids;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Mixin for BarrierBlock to support hotBath fluid waterlogging.
 * Auto-generated by generate_waterlogging_mixins.py
 * 
 * Supports:
 * - Setting WATERLOGGED=true when placing block in hotBath fluid
 * - Placing hotBath fluids into non-waterlogged blocks
 * - Replacing existing waterlogged fluid with a different hotBath fluid
 * 
 * Priority 500 ensures we run before other mods' mixins.
 */
@Mixin(value = BarrierBlock.class, priority = 500)
public abstract class BarrierBlockMixin extends Block implements SimpleWaterloggedBlock {

    public BarrierBlockMixin(Properties properties) {
        super(properties);
    }

    /**
     * Modify getStateForPlacement to set WATERLOGGED=true when placing in hotBath fluid.
     * Vanilla only checks for Fluids.WATER, not FluidTags.WATER, so we need to fix this.
     * This also stores the hotBath fluid type for later retrieval.
     */
    @Inject(method = "getStateForPlacement", at = @At("RETURN"), cancellable = true)
    private void hotbath$getStateForPlacement(BlockPlaceContext context, CallbackInfoReturnable<BlockState> cir) {
        BlockState result = cir.getReturnValue();
        if (result == null) return;
        if (!result.hasProperty(BlockStateProperties.WATERLOGGED)) return;
        BlockPos pos = context.getClickedPos();
        FluidState fluidState = context.getLevel().getFluidState(pos);
        Fluid fluid = fluidState.getType();
        // Check if placing in a hotBath fluid
        if (HotbathFluidHelper.isHotbathFluid(fluid)) {
            // Vanilla returned WATERLOGGED=false because it only checks Fluids.WATER
            // We need to set it to true and store the fluid type
            if (!result.getValue(BlockStateProperties.WATERLOGGED)) {
                result = result.setValue(BlockStateProperties.WATERLOGGED, true);
                cir.setReturnValue(result);
            }
            // Store the hotBath fluid type
            Fluid sourceFluid = hotbath$getSourceFluid(fluid);
            HotbathWaterloggingHelper.storeFluidTypeWithCustomId(context.getLevel(), pos, sourceFluid);
        }
    }

    @Inject(method = "canPlaceLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$canPlaceLiquid(BlockGetter level, BlockPos pos, BlockState state, Fluid fluid,
                                         CallbackInfoReturnable<Boolean> cir) {
        // Only handle hotBath fluids
        if (!HotbathFluidHelper.isHotbathFluid(fluid)) {
            return;
        }
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        if (!isWaterlogged) {
            // Not waterlogged, can place hotBath fluid
            cir.setReturnValue(true);
        } else {
            // Already waterlogged - check if we can replace with different fluid
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
            Fluid sourceFluid = hotbath$getSourceFluid(fluid);
                // Allow if stored is vanilla water or a different hotBath fluid
            if (storedFluid == null || storedFluid == Fluids.WATER || storedFluid == Fluids.EMPTY) {
                cir.setReturnValue(true);
            } else if (storedFluid != sourceFluid) {
                // Different hotBath fluid, allow replacement
                cir.setReturnValue(true);
            }
            // Same fluid - don't return, let vanilla handle (return false)
        }
    }

    @Inject(method = "placeLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$placeLiquid(LevelAccessor level, BlockPos pos, BlockState state, FluidState fluidState,
                                      CallbackInfoReturnable<Boolean> cir) {
        // Only handle hotBath fluids
        if (!HotbathFluidHelper.isHotbathFluid(fluidState.getType())) {
            return;
        }
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        // DEFENSIVE: Get fresh block state from world
        BlockState currentState = level.getBlockState(pos);
        if (!currentState.is(state.getBlock())) {
            cir.setReturnValue(false);
            return;
        }
        // Store the SOURCE fluid type
        Fluid fluidToStore = hotbath$getSourceFluid(fluidState.getType());
        HotbathWaterloggingHelper.storeFluidTypeWithCustomId(level, pos, fluidToStore);
        if (!isWaterlogged) {
            // Not waterlogged yet - set waterlogged state
            BlockState newState = currentState.setValue(BlockStateProperties.WATERLOGGED, true);
            boolean success = level.setBlock(pos, newState, 3);
                if (success) {
                level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
                        // DEFENSIVE: Verify
                BlockState verifyState = level.getBlockState(pos);
                if (!verifyState.hasProperty(BlockStateProperties.WATERLOGGED) 
                        || !verifyState.getValue(BlockStateProperties.WATERLOGGED)) {
                    level.setBlock(pos, newState, 2 | 16 | 32 | 64);
                }
            } else {
                HotbathWaterloggingHelper.removeFluidType(level, pos);
            }
            cir.setReturnValue(success);
        } else {
            // Already waterlogged - just replacing fluid, no block state change needed
            level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
            cir.setReturnValue(true);
        }
    }

    @Inject(method = "pickupBlock", at = @At("HEAD"), cancellable = true)
    private void hotbath$pickupBlock(LevelAccessor level, BlockPos pos, BlockState state,
                                      CallbackInfoReturnable<ItemStack> cir) {
        if (state.getValue(BlockStateProperties.WATERLOGGED)) {
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
                if (storedFluid != null && storedFluid != Fluids.WATER && storedFluid != Fluids.EMPTY) {
                // DEFENSIVE: Get fresh state from world
                BlockState currentState = level.getBlockState(pos);
                if (currentState.hasProperty(BlockStateProperties.WATERLOGGED)) {
                    level.setBlock(pos, currentState.setValue(BlockStateProperties.WATERLOGGED, false), 3);
                }
                        HotbathWaterloggingHelper.removeFluidType(level, pos);
                HotbathWaterloggingHelper.removeFromClientCache(pos);
                        ItemStack bucket = HotbathWaterloggingHelper.createBucketForFluid(storedFluid, pos);
                if (!bucket.isEmpty() && bucket.getItem() != Items.AIR) {
                    cir.setReturnValue(bucket);
                }
            }
        }
    }
    
    /**
     * Get the source fluid from a potentially flowing fluid.
     */
    @Unique
    private static Fluid hotbath$getSourceFluid(Fluid fluid) {
        if (fluid instanceof FlowingFluid flowingFluid) {
            return flowingFluid.getSource();
        }
        return fluid;
    }
}
