package com.crabmod.hotbath.mixin;

import com.crabmod.hotbath.waterlogging.HotbathWaterloggingHelper;
import net.minecraft.core.BlockPos;
import net.minecraft.tags.FluidTags;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.CandleBlock;
import net.minecraft.world.level.block.SimpleWaterloggedBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.level.material.Fluids;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Mixin for CandleBlock to support hotBath fluid waterlogging.
 * Auto-generated by generate_waterlogging_mixins.py
 */
@Mixin(CandleBlock.class)
public abstract class CandleBlockMixin extends Block implements SimpleWaterloggedBlock {

    public CandleBlockMixin(Properties properties) {
        super(properties);
    }

    @Inject(method = "canPlaceLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$canPlaceLiquid(BlockGetter level, BlockPos pos, BlockState state, Fluid fluid,
                                         CallbackInfoReturnable<Boolean> cir) {
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        boolean isWaterTagFluid = fluid.defaultFluidState().is(FluidTags.WATER);
        if (!isWaterlogged && isWaterTagFluid) {
            cir.setReturnValue(true);
        }
    }

    @Inject(method = "placeLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$placeLiquid(LevelAccessor level, BlockPos pos, BlockState state, FluidState fluidState,
                                      CallbackInfoReturnable<Boolean> cir) {
        if (fluidState.is(FluidTags.WATER) && !state.getValue(BlockStateProperties.WATERLOGGED)) {
            // Store the fluid type for later retrieval
            HotbathWaterloggingHelper.storeFluidType(level, pos, fluidState.getType());
            // Always set the block state (both client and server)
            level.setBlock(pos, state.setValue(BlockStateProperties.WATERLOGGED, true), 3);
            level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
            cir.setReturnValue(true);
        }
    }

    @Inject(method = "pickupBlock", at = @At("HEAD"), cancellable = true)
    private void hotbath$pickupBlock(LevelAccessor level, BlockPos pos, BlockState state,
                                      CallbackInfoReturnable<ItemStack> cir) {
        if (state.getValue(BlockStateProperties.WATERLOGGED)) {
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
                if (storedFluid != null && storedFluid != Fluids.WATER && storedFluid != Fluids.EMPTY) {
                level.setBlock(pos, state.setValue(BlockStateProperties.WATERLOGGED, false), 3);
                HotbathWaterloggingHelper.removeFluidType(level, pos);
                HotbathWaterloggingHelper.removeFromClientCache(pos);
                        ItemStack bucket = new ItemStack(storedFluid.getBucket());
                if (!bucket.isEmpty() && bucket.getItem() != Items.AIR) {
                    cir.setReturnValue(bucket);
                }
            }
        }
    }
}
