package com.crabmod.hotbath.mixin;

import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that checks for compatibility mode and waterlogging settings before loading mixins.
 * 
 * Config Priority:
 * 1. compatibilityMode = true -> ALL mixins disabled (except FishingHookMixin)
 * 2. enableWaterlogging = false -> Waterlogging mixins disabled, other mixins still work
 * 
 * SAVE SAFETY:
 * - Disabling waterlogging does NOT corrupt world data
 * - Existing waterlogged blocks will display as vanilla water
 * - Data is preserved and will be restored when re-enabled
 * 
 * This reads the config file directly since Forge config is not available at mixin load time.
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class HotBathMixinPlugin implements IMixinConfigPlugin {
    
    private static boolean compatibilityMode = false;
    private static boolean waterloggingEnabled = true;
    private static boolean configChecked = false;
    
    // List of waterlogging-related mixin class names (without package)
    private static final Set<String> WATERLOGGING_MIXINS = Set.of(
        "SimpleWaterloggedBlockMixin",
        "LevelFluidStateMixin",
        "FlowingFluidMixin",
        "StairBlockMixin", "SlabBlockMixin", "TrapDoorBlockMixin", "FenceBlockMixin",
        "FenceGateBlockMixin", "WallBlockMixin", "LadderBlockMixin", "ChainBlockMixin",
        "LanternBlockMixin", "CampfireBlockMixin", "SignBlockMixin", "ConduitBlockMixin",
        "SeaPickleBlockMixin", "ScaffoldingBlockMixin", "LightningRodBlockMixin",
        "PointedDripstoneBlockMixin", "AmethystClusterBlockMixin", "BigDripleafBlockMixin",
        "BigDripleafStemBlockMixin", "SmallDripleafBlockMixin", "HangingRootsBlockMixin",
        "MangrovePropaguleBlockMixin", "MangroveRootsBlockMixin", "SculkSensorBlockMixin",
        "SculkShriekerBlockMixin", "SculkVeinBlockMixin", "GlowLichenBlockMixin",
        "CandleBlockMixin", "DecoratedPotBlockMixin", "ChestBlockMixin", "EnderChestBlockMixin",
        "LeavesBlockMixin", "LightBlockMixin", "BarrierBlockMixin",
        "SeagrassBlockMixin", "KelpBlockMixin", "KelpPlantBlockMixin", "TallSeagrassBlockMixin",
        "BaseCoralPlantTypeBlockMixin", "BaseCoralWallFanBlockMixin",
        "CoralPlantBlockMixin", "CoralFanBlockMixin", "CoralWallFanBlockMixin"
    );
    
    // Client-side waterlogging mixins
    private static final Set<String> CLIENT_WATERLOGGING_MIXINS = Set.of(
        "BlockRenderDispatcherMixin",
        "LiquidBlockRendererMixin"
    );
    
    static {
        checkConfig();
    }
    
    /**
     * Check config settings by reading the config file directly.
     * This is necessary because Forge config is not available at mixin load time.
     */
    private static void checkConfig() {
        if (configChecked) {
            return;
        }
        configChecked = true;
        
        try {
            // Try to find the config file in common locations
            Path configDir = Path.of("config");
            Path configFile = configDir.resolve("hotbath-common.toml");
            
            if (Files.exists(configFile)) {
                String content = Files.readString(configFile);
                // Parse the TOML file for settings
                for (String line : content.split("\\n")) {
                    line = line.trim();
                    if (line.startsWith("compatibilityMode")) {
                        if (line.contains("true")) {
                            compatibilityMode = true;
                            System.out.println("[HotBath] Compatibility mode enabled - disabling all advanced mixins");
                        }
                    } else if (line.startsWith("enableWaterlogging")) {
                        if (line.contains("false")) {
                            waterloggingEnabled = false;
                            System.out.println("[HotBath] Waterlogging disabled in config");
                        }
                    }
                }
            }
        } catch (IOException e) {
            // Config not found or not readable, use defaults
            System.out.println("[HotBath] Could not read config file, using default settings");
        }
        
        // Log final state
        if (!compatibilityMode && !waterloggingEnabled) {
            System.out.println("[HotBath] Waterlogging mixins will be disabled, other features remain active");
        }
    }
    
    /**
     * Check if compatibility mode is enabled.
     * @return true if compatibility mode is enabled
     */
    public static boolean isCompatibilityModeEnabled() {
        return compatibilityMode;
    }
    
    /**
     * Check if waterlogging is enabled.
     * @return true if waterlogging is enabled (and compatibility mode is off)
     */
    public static boolean isWaterloggingEnabled() {
        return !compatibilityMode && waterloggingEnabled;
    }
    
    @Override
    public void onLoad(String mixinPackage) {
        // No initialization needed
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Extract simple class name from full mixin class name
        String simpleName = mixinClassName;
        int lastDot = mixinClassName.lastIndexOf('.');
        if (lastDot >= 0) {
            simpleName = mixinClassName.substring(lastDot + 1);
        }
        
        // FishingHookMixin is always allowed - it just prevents fishing in bath water
        if (simpleName.equals("FishingHookMixin")) {
            return true;
        }
        
        // If compatibility mode is enabled, disable everything else
        if (compatibilityMode) {
            return false;
        }
        
        // If waterlogging is disabled, disable waterlogging-related mixins
        if (!waterloggingEnabled) {
            if (WATERLOGGING_MIXINS.contains(simpleName) || CLIENT_WATERLOGGING_MIXINS.contains(simpleName)) {
                return false;
            }
        }
        
        return true;
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // No special target handling needed
    }
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No pre-apply handling needed
    }
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No post-apply handling needed
    }
}
