package com.crabmod.hotbath.mixin;

import com.crabmod.hotbath.waterlogging.HotbathWaterloggingHelper;
import net.minecraft.core.BlockPos;
import net.minecraft.tags.FluidTags;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.LightBlock;
import net.minecraft.world.level.block.SimpleWaterloggedBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.level.material.Fluids;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Mixin for LightBlock to support hotBath fluid waterlogging.
 * Auto-generated by generate_waterlogging_mixins.py
 * 
 * Priority 500 ensures we run before other mods' mixins.
 */
@Mixin(value = LightBlock.class, priority = 500)
public abstract class LightBlockMixin extends Block implements SimpleWaterloggedBlock {

    public LightBlockMixin(Properties properties) {
        super(properties);
    }

    @Inject(method = "canPlaceLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$canPlaceLiquid(BlockGetter level, BlockPos pos, BlockState state, Fluid fluid,
                                         CallbackInfoReturnable<Boolean> cir) {
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        boolean isWaterTagFluid = fluid.defaultFluidState().is(FluidTags.WATER);
        if (!isWaterlogged && isWaterTagFluid) {
            cir.setReturnValue(true);
        }
    }

    @Inject(method = "placeLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$placeLiquid(LevelAccessor level, BlockPos pos, BlockState state, FluidState fluidState,
                                      CallbackInfoReturnable<Boolean> cir) {
        if (fluidState.is(FluidTags.WATER) && !state.getValue(BlockStateProperties.WATERLOGGED)) {
            // DEFENSIVE: Get fresh block state from world to ensure we have the latest
            BlockState currentState = level.getBlockState(pos);
                // Verify the block is still the same type and not already waterlogged
            if (!currentState.is(state.getBlock())) {
                cir.setReturnValue(false);
                return;
            }
                if (currentState.hasProperty(BlockStateProperties.WATERLOGGED) 
                    && currentState.getValue(BlockStateProperties.WATERLOGGED)) {
                cir.setReturnValue(false);
                return;
            }
                // Store the fluid type for later retrieval
            HotbathWaterloggingHelper.storeFluidType(level, pos, fluidState.getType());
                // DEFENSIVE: Create new state from current world state
            BlockState newState = currentState.setValue(BlockStateProperties.WATERLOGGED, true);
                // Set the block state with flag 3 (notify clients + neighbors)
            boolean success = level.setBlock(pos, newState, 3);
                if (success) {
                level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
                        // DEFENSIVE: Verify the block was actually set correctly
                BlockState verifyState = level.getBlockState(pos);
                if (!verifyState.hasProperty(BlockStateProperties.WATERLOGGED) 
                        || !verifyState.getValue(BlockStateProperties.WATERLOGGED)) {
                    level.setBlock(pos, newState, 2 | 16 | 32 | 64);
                }
            } else {
                HotbathWaterloggingHelper.removeFluidType(level, pos);
            }
                cir.setReturnValue(success);
        }
    }

    @Inject(method = "pickupBlock", at = @At("HEAD"), cancellable = true)
    private void hotbath$pickupBlock(LevelAccessor level, BlockPos pos, BlockState state,
                                      CallbackInfoReturnable<ItemStack> cir) {
        if (state.getValue(BlockStateProperties.WATERLOGGED)) {
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
                if (storedFluid != null && storedFluid != Fluids.WATER && storedFluid != Fluids.EMPTY) {
                // DEFENSIVE: Get fresh state from world
                BlockState currentState = level.getBlockState(pos);
                if (currentState.hasProperty(BlockStateProperties.WATERLOGGED)) {
                    level.setBlock(pos, currentState.setValue(BlockStateProperties.WATERLOGGED, false), 3);
                }
                        HotbathWaterloggingHelper.removeFluidType(level, pos);
                HotbathWaterloggingHelper.removeFromClientCache(pos);
                        ItemStack bucket = new ItemStack(storedFluid.getBucket());
                if (!bucket.isEmpty() && bucket.getItem() != Items.AIR) {
                    cir.setReturnValue(bucket);
                }
            }
        }
    }
}
