package com.crabmod.hotbath.mixin.sodium;

import com.crabmod.hotbath.mixin.HotBathMixinPlugin;
import net.neoforged.fml.loading.FMLLoader;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that conditionally loads Sodium compatibility mixins only when:
 * 1. Sodium is present
 * 2. Waterlogging is enabled (or compatibility mode is off)
 * 
 * Sodium replaces vanilla's chunk rendering system with its own optimized pipeline,
 * which bypasses our BlockRenderDispatcherMixin. This plugin enables Sodium-specific
 * mixins to intercept the fluid rendering at the right point.
 * 
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class SodiumMixinPlugin implements IMixinConfigPlugin {
    
    private static Boolean sodiumLoaded = null;
    
    /**
     * Check if Sodium is present using NeoForge's mod loading API.
     */
    private static boolean checkSodiumPresent() {
        if (sodiumLoaded == null) {
            try {
                // Use NeoForge's FMLLoader API to check if sodium mod is in the loading list
                sodiumLoaded = FMLLoader.getLoadingModList().getModFileById("sodium") != null;
                
                if (sodiumLoaded) {
                    System.out.println("[HotBath] Sodium detected via FMLLoader");
                } else {
                    System.out.println("[HotBath] Sodium not detected, Sodium mixins will be skipped");
                }
            } catch (Throwable t) {
                // Fallback: if FMLLoader is not available, try ClassLoader.getResource
                String classPath = "net/caffeinemc/mods/sodium/neoforge/render/FluidRendererImpl.class";
                sodiumLoaded = SodiumMixinPlugin.class.getClassLoader().getResource(classPath) != null;
                System.out.println("[HotBath] Used fallback detection for Sodium: " + sodiumLoaded);
            }
        }
        return sodiumLoaded;
    }
    
    /**
     * Check if Sodium is loaded.
     * @return true if Sodium is present
     */
    public static boolean isSodiumLoaded() {
        return checkSodiumPresent();
    }
    
    @Override
    public void onLoad(String mixinPackage) {
        // Check early but don't force class loading
        checkSodiumPresent();
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // First check: Is Sodium even loaded?
        if (!checkSodiumPresent()) {
            return false;
        }
        
        // Second check: Is waterlogging enabled?
        // Sodium mixins are for waterlogging fluid rendering
        if (!HotBathMixinPlugin.isWaterloggingEnabled()) {
            System.out.println("[HotBath] Sodium mixin skipped - waterlogging is disabled");
            return false;
        }
        
        System.out.println("[HotBath] Enabling Sodium compatibility mixin: " + mixinClassName);
        return true;
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // No special target handling needed
    }
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No pre-apply handling needed
    }
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No post-apply handling needed
    }
}
