#!/usr/bin/env python3
"""
Script to generate Mixin classes for all blocks that implement SimpleWaterloggedBlock.
This enables hotBath fluids to be placed in any waterloggable block.

Also generates the HotBathMixinPlugin for compatibility mode support.
When compatibility mode is enabled, all mixins, mod integrations, and waterlogging are disabled.
"""

import os
from pathlib import Path

# All Minecraft block classes that implement SimpleWaterloggedBlock
# Found by searching: implements.*SimpleWaterloggedBlock
# Note: Some blocks are only in certain MC versions, adjust as needed
WATERLOGGED_BLOCKS = [
    # Basic blocks with WATERLOGGED property
    "StairBlock",
    "SlabBlock",
    "TrapDoorBlock",
    "FenceBlock",
    "FenceGateBlock",
    "WallBlock",
    "LadderBlock",
    "ChainBlock",
    "LanternBlock",
    "CampfireBlock",
    "SignBlock",
    # "HangingSignBlock",  # 1.20.2+ only
    "ConduitBlock",
    "SeaPickleBlock",
    "ScaffoldingBlock",
    "LightningRodBlock",
    "PointedDripstoneBlock",
    "AmethystClusterBlock",
    "BigDripleafBlock",
    "BigDripleafStemBlock",
    "SmallDripleafBlock",
    "HangingRootsBlock",
    "MangrovePropaguleBlock",
    "MangroveRootsBlock",
    "SculkSensorBlock",
    "SculkShriekerBlock",
    "SculkVeinBlock",
    "GlowLichenBlock",
    "CandleBlock",
    "DecoratedPotBlock",
    "ChestBlock",
    "EnderChestBlock",
    "LeavesBlock",
    "LightBlock",
    "BarrierBlock",
    # "HeavyCoreBlock",  # 1.21+ only
    # Abstract/parent classes (skip these as they're extended by others)
    # "BaseCoralPlantTypeBlock",  # Extended by coral blocks
    # "BaseRailBlock",  # Extended by rail blocks
    # "CrossCollisionBlock",  # Parent of FenceBlock, WallBlock, IronBarsBlock
    # "WaterloggedTransparentBlock",  # Parent class
]

# Blocks that need special handling (different canPlaceLiquid logic)
SPECIAL_BLOCKS = {
    "SlabBlock": "state.getValue(SlabBlock.TYPE) != SlabType.DOUBLE",
    "ScaffoldingBlock": "true",  # Always allow
}

# Additional imports needed for specific blocks
EXTRA_IMPORTS = {
    "SlabBlock": [
        "import net.minecraft.world.level.block.state.properties.SlabType;",
    ],
}

# ============================================================================
# Mixin Plugin Template - Handles compatibility mode detection at mixin load time
# ============================================================================
MIXIN_PLUGIN_TEMPLATE = '''package com.crabmod.hotbath.mixin;

import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that checks for compatibility mode and waterlogging settings before loading mixins.
 * 
 * Config Priority:
 * 1. compatibilityMode = true -> ALL mixins disabled (except FishingHookMixin)
 * 2. enableWaterlogging = false -> Waterlogging mixins disabled, other mixins still work
 * 
 * SAVE SAFETY:
 * - Disabling waterlogging does NOT corrupt world data
 * - Existing waterlogged blocks will display as vanilla water
 * - Data is preserved and will be restored when re-enabled
 * 
 * This reads the config file directly since Forge config is not available at mixin load time.
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class HotBathMixinPlugin implements IMixinConfigPlugin {
    
    private static boolean compatibilityMode = false;
    private static boolean waterloggingEnabled = true;
    private static boolean configChecked = false;
    
    // List of waterlogging-related mixin class names (without package)
    private static final Set<String> WATERLOGGING_MIXINS = Set.of(
        "StairBlockMixin", "SlabBlockMixin", "TrapDoorBlockMixin", "FenceBlockMixin",
        "FenceGateBlockMixin", "WallBlockMixin", "LadderBlockMixin", "ChainBlockMixin",
        "LanternBlockMixin", "CampfireBlockMixin", "SignBlockMixin", "ConduitBlockMixin",
        "SeaPickleBlockMixin", "ScaffoldingBlockMixin", "LightningRodBlockMixin",
        "PointedDripstoneBlockMixin", "AmethystClusterBlockMixin", "BigDripleafBlockMixin",
        "BigDripleafStemBlockMixin", "SmallDripleafBlockMixin", "HangingRootsBlockMixin",
        "MangrovePropaguleBlockMixin", "MangroveRootsBlockMixin", "SculkSensorBlockMixin",
        "SculkShriekerBlockMixin", "SculkVeinBlockMixin", "GlowLichenBlockMixin",
        "CandleBlockMixin", "DecoratedPotBlockMixin", "ChestBlockMixin", "EnderChestBlockMixin",
        "LeavesBlockMixin", "LightBlockMixin", "BarrierBlockMixin", "LevelFluidStateMixin"
    );
    
    static {
        checkConfig();
    }
    
    /**
     * Check config settings by reading the config file directly.
     * This is necessary because Forge config is not available at mixin load time.
     */
    private static void checkConfig() {
        if (configChecked) {
            return;
        }
        configChecked = true;
        
        try {
            // Try to find the config file in common locations
            Path configDir = Path.of("config");
            Path configFile = configDir.resolve("hotbath-common.toml");
            
            if (Files.exists(configFile)) {
                String content = Files.readString(configFile);
                // Parse the TOML file for settings
                for (String line : content.split("\\\\n")) {
                    line = line.trim();
                    if (line.startsWith("compatibilityMode")) {
                        if (line.contains("true")) {
                            compatibilityMode = true;
                            System.out.println("[HotBath] Compatibility mode enabled - disabling all advanced mixins");
                        }
                    } else if (line.startsWith("enableWaterlogging")) {
                        if (line.contains("false")) {
                            waterloggingEnabled = false;
                            System.out.println("[HotBath] Waterlogging disabled in config");
                        }
                    }
                }
            }
        } catch (IOException e) {
            // Config not found or not readable, use defaults
            System.out.println("[HotBath] Could not read config file, using default settings");
        }
        
        // Log final state
        if (!compatibilityMode && !waterloggingEnabled) {
            System.out.println("[HotBath] Waterlogging mixins will be disabled, other features remain active");
        }
    }
    
    /**
     * Check if compatibility mode is enabled.
     * @return true if compatibility mode is enabled
     */
    public static boolean isCompatibilityModeEnabled() {
        return compatibilityMode;
    }
    
    /**
     * Check if waterlogging is enabled.
     * @return true if waterlogging is enabled (and compatibility mode is off)
     */
    public static boolean isWaterloggingEnabled() {
        return !compatibilityMode && waterloggingEnabled;
    }
    
    @Override
    public void onLoad(String mixinPackage) {
        // No initialization needed
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Extract simple class name from full mixin class name
        String simpleName = mixinClassName;
        int lastDot = mixinClassName.lastIndexOf('.');
        if (lastDot >= 0) {
            simpleName = mixinClassName.substring(lastDot + 1);
        }
        
        // FishingHookMixin is always allowed - it just prevents fishing in bath water
        if (simpleName.equals("FishingHookMixin")) {
            return true;
        }
        
        // If compatibility mode is enabled, disable everything else
        if (compatibilityMode) {
            return false;
        }
        
        // If waterlogging is disabled, only disable waterlogging-related mixins
        if (!waterloggingEnabled && WATERLOGGING_MIXINS.contains(simpleName)) {
            return false;
        }
        
        return true;
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // No special target handling needed
    }
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No pre-apply handling needed
    }
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No post-apply handling needed
    }
}
'''

# ============================================================================
# Client Mixin Plugin Template - For client-side mixins
# ============================================================================
CLIENT_MIXIN_PLUGIN_TEMPLATE = '''package com.crabmod.hotbath.mixin.client;

import com.crabmod.hotbath.mixin.HotBathMixinPlugin;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.util.List;
import java.util.Set;

/**
 * Client-side mixin plugin that delegates to the main HotBathMixinPlugin.
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class HotBathClientMixinPlugin implements IMixinConfigPlugin {
    
    @Override
    public void onLoad(String mixinPackage) {
        // No initialization needed
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Delegate to main plugin - disable all client mixins in compatibility mode
        return !HotBathMixinPlugin.isCompatibilityModeEnabled();
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // No special target handling needed
    }
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No pre-apply handling needed
    }
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No post-apply handling needed
    }
}
'''

MIXIN_TEMPLATE = '''package com.crabmod.hotbath.mixin;

import com.crabmod.hotbath.util.HotbathFluidHelper;
import com.crabmod.hotbath.waterlogging.HotbathWaterloggingHelper;
import net.minecraft.core.BlockPos;
import net.minecraft.tags.FluidTags;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.{block_class};
import net.minecraft.world.level.block.SimpleWaterloggedBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.FlowingFluid;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.level.material.Fluids;
{extra_imports}import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Mixin for {block_class} to support hotBath fluid waterlogging.
 * Auto-generated by generate_waterlogging_mixins.py
 * 
 * Supports:
 * - Setting WATERLOGGED=true when placing block in hotBath fluid
 * - Placing hotBath fluids into non-waterlogged blocks
 * - Replacing existing waterlogged fluid with a different hotBath fluid
 * 
 * Priority 500 ensures we run before other mods' mixins.
 */
@Mixin(value = {block_class}.class, priority = 500)
public abstract class {block_class}Mixin extends Block implements SimpleWaterloggedBlock {{

    public {block_class}Mixin(Properties properties) {{
        super(properties);
    }}

    /**
     * Modify getStateForPlacement to set WATERLOGGED=true when placing in hotBath fluid.
     * Vanilla only checks for Fluids.WATER, not FluidTags.WATER, so we need to fix this.
     * This also stores the hotBath fluid type for later retrieval.
     */
    @Inject(method = "getStateForPlacement", at = @At("RETURN"), cancellable = true)
    private void hotbath$getStateForPlacement(BlockPlaceContext context, CallbackInfoReturnable<BlockState> cir) {{
        BlockState result = cir.getReturnValue();
        if (result == null) return;
        if (!result.hasProperty(BlockStateProperties.WATERLOGGED)) return;
        
        BlockPos pos = context.getClickedPos();
        FluidState fluidState = context.getLevel().getFluidState(pos);
        Fluid fluid = fluidState.getType();
        
        // Check if placing in a hotBath fluid
        if (HotbathFluidHelper.isHotbathFluid(fluid)) {{
            // Vanilla returned WATERLOGGED=false because it only checks Fluids.WATER
            // We need to set it to true and store the fluid type
            if (!result.getValue(BlockStateProperties.WATERLOGGED)) {{
                result = result.setValue(BlockStateProperties.WATERLOGGED, true);
                cir.setReturnValue(result);
            }}
            // Store the hotBath fluid type
            Fluid sourceFluid = hotbath$getSourceFluid(fluid);
            HotbathWaterloggingHelper.storeFluidTypeWithCustomId(context.getLevel(), pos, sourceFluid);
        }}
    }}

    @Inject(method = "canPlaceLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$canPlaceLiquid(BlockGetter level, BlockPos pos, BlockState state, Fluid fluid,
                                         CallbackInfoReturnable<Boolean> cir) {{
        {can_place_check}
        // Only handle hotBath fluids
        if (!HotbathFluidHelper.isHotbathFluid(fluid)) {{
            return;
        }}
        
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        if (!isWaterlogged) {{
            // Not waterlogged, can place hotBath fluid
            cir.setReturnValue(true);
        }} else {{
            // Already waterlogged - check if we can replace with different fluid
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
            Fluid sourceFluid = hotbath$getSourceFluid(fluid);
            
            // Allow if stored is vanilla water or a different hotBath fluid
            if (storedFluid == null || storedFluid == Fluids.WATER || storedFluid == Fluids.EMPTY) {{
                cir.setReturnValue(true);
            }} else if (storedFluid != sourceFluid) {{
                // Different hotBath fluid, allow replacement
                cir.setReturnValue(true);
            }}
            // Same fluid - don't return, let vanilla handle (return false)
        }}
        {can_place_end}
    }}

    @Inject(method = "placeLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$placeLiquid(LevelAccessor level, BlockPos pos, BlockState state, FluidState fluidState,
                                      CallbackInfoReturnable<Boolean> cir) {{
        {place_check}
        // Only handle hotBath fluids
        if (!HotbathFluidHelper.isHotbathFluid(fluidState.getType())) {{
            return;
        }}
        
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        
        // DEFENSIVE: Get fresh block state from world
        BlockState currentState = level.getBlockState(pos);
        if (!currentState.is(state.getBlock())) {{
            cir.setReturnValue(false);
            return;
        }}
        
        // Store the SOURCE fluid type
        Fluid fluidToStore = hotbath$getSourceFluid(fluidState.getType());
        HotbathWaterloggingHelper.storeFluidTypeWithCustomId(level, pos, fluidToStore);
        
        if (!isWaterlogged) {{
            // Not waterlogged yet - set waterlogged state
            BlockState newState = currentState.setValue(BlockStateProperties.WATERLOGGED, true);
            boolean success = level.setBlock(pos, newState, 3);
            
            if (success) {{
                level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
                
                // DEFENSIVE: Verify
                BlockState verifyState = level.getBlockState(pos);
                if (!verifyState.hasProperty(BlockStateProperties.WATERLOGGED) 
                        || !verifyState.getValue(BlockStateProperties.WATERLOGGED)) {{
                    level.setBlock(pos, newState, 2 | 16 | 32 | 64);
                }}
            }} else {{
                HotbathWaterloggingHelper.removeFluidType(level, pos);
            }}
            cir.setReturnValue(success);
        }} else {{
            // Already waterlogged - just replacing fluid, no block state change needed
            level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
            cir.setReturnValue(true);
        }}
        {place_end}
    }}

    @Inject(method = "pickupBlock", at = @At("HEAD"), cancellable = true)
    private void hotbath$pickupBlock(LevelAccessor level, BlockPos pos, BlockState state,
                                      CallbackInfoReturnable<ItemStack> cir) {{
        {pickup_check}
        if (state.getValue(BlockStateProperties.WATERLOGGED)) {{
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
            
            if (storedFluid != null && storedFluid != Fluids.WATER && storedFluid != Fluids.EMPTY) {{
                // DEFENSIVE: Get fresh state from world
                BlockState currentState = level.getBlockState(pos);
                if (currentState.hasProperty(BlockStateProperties.WATERLOGGED)) {{
                    level.setBlock(pos, currentState.setValue(BlockStateProperties.WATERLOGGED, false), 3);
                }}
                
                HotbathWaterloggingHelper.removeFluidType(level, pos);
                HotbathWaterloggingHelper.removeFromClientCache(pos);
                
                ItemStack bucket = HotbathWaterloggingHelper.createBucketForFluid(storedFluid, pos);
                if (!bucket.isEmpty() && bucket.getItem() != Items.AIR) {{
                    cir.setReturnValue(bucket);
                }}
            }}
        }}
        {pickup_end}
    }}
    
    /**
     * Get the source fluid from a potentially flowing fluid.
     */
    @Unique
    private static Fluid hotbath$getSourceFluid(Fluid fluid) {{
        if (fluid instanceof FlowingFluid flowingFluid) {{
            return flowingFluid.getSource();
        }}
        return fluid;
    }}
}}
'''

def generate_mixin(block_class: str, output_dir: Path) -> str:
    """Generate a mixin class for the given block class."""
    
    # Check for special handling
    special_check = SPECIAL_BLOCKS.get(block_class)
    
    if special_check:
        can_place_check = f"if ({special_check}) {{"
        can_place_end = "}"
        place_check = f"if ({special_check}) {{"
        place_end = "}"
        pickup_check = f"if ({special_check}) {{"
        pickup_end = "}"
    else:
        can_place_check = ""
        can_place_end = ""
        place_check = ""
        place_end = ""
        pickup_check = ""
        pickup_end = ""
    
    # Get extra imports
    extra_imports = ""
    if block_class in EXTRA_IMPORTS:
        extra_imports = "\n".join(EXTRA_IMPORTS[block_class]) + "\n"
    
    content = MIXIN_TEMPLATE.format(
        block_class=block_class,
        extra_imports=extra_imports,
        can_place_check=can_place_check,
        can_place_end=can_place_end,
        place_check=place_check,
        place_end=place_end,
        pickup_check=pickup_check,
        pickup_end=pickup_end,
    )
    
    # Clean up empty lines for non-special blocks
    if not special_check:
        content = content.replace("        \n", "")
    
    output_file = output_dir / f"{block_class}Mixin.java"
    
    return content, output_file


def generate_mixins_json(blocks: list[str]) -> str:
    """Generate the mixins.json content with plugin support for compatibility mode."""
    # Keep existing mixins that are not auto-generated
    mixin_list = ["FishingHookMixin", "LevelFluidStateMixin"]
    mixin_list.extend([f"{block}Mixin" for block in blocks])
    
    mixins_str = ",\n    ".join([f'"{m}"' for m in mixin_list])
    
    return f'''{{
  "required": true,
  "minVersion": "0.8",
  "package": "com.crabmod.hotbath.mixin",
  "compatibilityLevel": "JAVA_17",
  "refmap": "hotbath.refmap.json",
  "plugin": "com.crabmod.hotbath.mixin.HotBathMixinPlugin",
  "mixins": [
    {mixins_str}
  ],
  "client": ["client.BlockRenderDispatcherMixin"],
  "injectors": {{
    "defaultRequire": 1
  }}
}}
'''


def main():
    # Get the script directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    mixin_dir = project_root / "src" / "main" / "java" / "com" / "crabmod" / "hotbath" / "mixin"
    client_mixin_dir = mixin_dir / "client"
    resources_dir = project_root / "src" / "main" / "resources"
    
    print(f"Generating mixins in: {mixin_dir}")
    
    # Ensure directories exist
    mixin_dir.mkdir(parents=True, exist_ok=True)
    client_mixin_dir.mkdir(parents=True, exist_ok=True)
    
    # ========================================
    # Generate HotBathMixinPlugin.java
    # ========================================
    plugin_file = mixin_dir / "HotBathMixinPlugin.java"
    plugin_file.write_text(MIXIN_PLUGIN_TEMPLATE, encoding='utf-8')
    print(f"  Generated: HotBathMixinPlugin.java")
    
    # ========================================
    # Generate HotBathClientMixinPlugin.java
    # ========================================
    client_plugin_file = client_mixin_dir / "HotBathClientMixinPlugin.java"
    client_plugin_file.write_text(CLIENT_MIXIN_PLUGIN_TEMPLATE, encoding='utf-8')
    print(f"  Generated: client/HotBathClientMixinPlugin.java")
    
    generated_files = []
    
    for block_class in WATERLOGGED_BLOCKS:
        content, output_file = generate_mixin(block_class, mixin_dir)
        
        # Only write if file doesn't exist or is different
        if output_file.exists():
            existing = output_file.read_text(encoding='utf-8')
            if existing == content:
                print(f"  Skipped (unchanged): {block_class}Mixin.java")
                generated_files.append(block_class)
                continue
        
        output_file.write_text(content, encoding='utf-8')
        print(f"  Generated: {block_class}Mixin.java")
        generated_files.append(block_class)
    
    # Generate mixins.json
    mixins_json = generate_mixins_json(generated_files)
    mixins_json_file = resources_dir / "hotbath.mixins.json"
    mixins_json_file.write_text(mixins_json, encoding='utf-8')
    print(f"\nUpdated: {mixins_json_file}")
    
    # ========================================
    # Update alexsmobs and alexscaves mixin plugins
    # ========================================
    update_mod_mixin_plugins(project_root)
    
    print(f"\n✅ Generated {len(generated_files)} mixin files + 2 plugin files")
    print("\n📋 Compatibility Mode:")
    print("   - When enabled in config, all waterlogging mixins are disabled")
    print("   - Mod integrations (Cold Sweat, LSO, etc.) are also disabled")
    print("   - Only basic fluid properties remain functional")
    print("\nNote: Some blocks may need manual adjustments if they have special waterlogging logic.")


def update_mod_mixin_plugins(project_root: Path):
    """Update the AlexsMobs and AlexsCaves mixin plugins to check compatibility mode."""
    
    alexsmobs_plugin = project_root / "src" / "main" / "java" / "com" / "crabmod" / "hotbath" / "mixin" / "alexsmobs" / "AlexsMobsMixinPlugin.java"
    alexscaves_plugin = project_root / "src" / "main" / "java" / "com" / "crabmod" / "hotbath" / "mixin" / "alexscaves" / "AlexsCavesMixinPlugin.java"
    
    # AlexsMobs plugin with compatibility mode check
    alexsmobs_content = '''package com.crabmod.hotbath.mixin.alexsmobs;

import com.crabmod.hotbath.mixin.HotBathMixinPlugin;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that conditionally loads Alex's Mobs mixins only when:
 * 1. The mod is present
 * 2. Compatibility mode is NOT enabled
 * 
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class AlexsMobsMixinPlugin implements IMixinConfigPlugin {
    
    private static boolean alexsMobsLoaded = false;
    
    static {
        try {
            Class.forName("com.github.alexthe666.alexsmobs.AlexsMobs");
            alexsMobsLoaded = true;
        } catch (ClassNotFoundException e) {
            alexsMobsLoaded = false;
        }
    }
    
    @Override
    public void onLoad(String mixinPackage) {
        // No initialization needed
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Disable if compatibility mode is enabled
        if (HotBathMixinPlugin.isCompatibilityModeEnabled()) {
            return false;
        }
        // Only apply mixins if Alex's Mobs is loaded
        return alexsMobsLoaded;
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // No special target handling needed
    }
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No pre-apply handling needed
    }
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No post-apply handling needed
    }
}
'''
    
    # AlexsCaves plugin with compatibility mode check
    alexscaves_content = '''package com.crabmod.hotbath.mixin.alexscaves;

import com.crabmod.hotbath.mixin.HotBathMixinPlugin;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that conditionally loads Alex's Caves mixins only when:
 * 1. The mod is present
 * 2. Compatibility mode is NOT enabled
 * 
 * Auto-generated by generate_waterlogging_mixins.py
 */
public class AlexsCavesMixinPlugin implements IMixinConfigPlugin {
    
    private static boolean alexsCavesLoaded = false;
    
    static {
        try {
            Class.forName("com.github.alexmodguy.alexscaves.AlexsCaves");
            alexsCavesLoaded = true;
        } catch (ClassNotFoundException e) {
            alexsCavesLoaded = false;
        }
    }
    
    @Override
    public void onLoad(String mixinPackage) {
        // No initialization needed
    }
    
    @Override
    public String getRefMapperConfig() {
        return null;
    }
    
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Disable if compatibility mode is enabled
        if (HotBathMixinPlugin.isCompatibilityModeEnabled()) {
            return false;
        }
        // Only apply mixins if Alex's Caves is loaded
        return alexsCavesLoaded;
    }
    
    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // No special target handling needed
    }
    
    @Override
    public List<String> getMixins() {
        return null;
    }
    
    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No pre-apply handling needed
    }
    
    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // No post-apply handling needed
    }
}
'''
    
    if alexsmobs_plugin.parent.exists():
        alexsmobs_plugin.write_text(alexsmobs_content, encoding='utf-8')
        print(f"  Updated: alexsmobs/AlexsMobsMixinPlugin.java")
    
    if alexscaves_plugin.parent.exists():
        alexscaves_plugin.write_text(alexscaves_content, encoding='utf-8')
        print(f"  Updated: alexscaves/AlexsCavesMixinPlugin.java")


if __name__ == "__main__":
    main()
