#!/usr/bin/env python3
"""
Script to generate Mixin classes for all blocks that implement SimpleWaterloggedBlock.
This enables hotBath fluids to be placed in any waterloggable block.
"""

import os
from pathlib import Path

# All Minecraft block classes that implement SimpleWaterloggedBlock
# Found by searching: implements.*SimpleWaterloggedBlock
# Note: Some blocks are only in certain MC versions, adjust as needed
WATERLOGGED_BLOCKS = [
    # Basic blocks with WATERLOGGED property
    "StairBlock",
    "SlabBlock",
    "TrapDoorBlock",
    "FenceBlock",
    "FenceGateBlock",
    "WallBlock",
    "LadderBlock",
    "ChainBlock",
    "LanternBlock",
    "CampfireBlock",
    "SignBlock",
    # "HangingSignBlock",  # 1.20.2+ only
    "ConduitBlock",
    "SeaPickleBlock",
    "ScaffoldingBlock",
    "LightningRodBlock",
    "PointedDripstoneBlock",
    "AmethystClusterBlock",
    "BigDripleafBlock",
    "BigDripleafStemBlock",
    "SmallDripleafBlock",
    "HangingRootsBlock",
    "MangrovePropaguleBlock",
    "MangroveRootsBlock",
    "SculkSensorBlock",
    "SculkShriekerBlock",
    "SculkVeinBlock",
    "GlowLichenBlock",
    "CandleBlock",
    "DecoratedPotBlock",
    "ChestBlock",
    "EnderChestBlock",
    "LeavesBlock",
    "LightBlock",
    "BarrierBlock",
    # "HeavyCoreBlock",  # 1.21+ only
    # Abstract/parent classes (skip these as they're extended by others)
    # "BaseCoralPlantTypeBlock",  # Extended by coral blocks
    # "BaseRailBlock",  # Extended by rail blocks
    # "CrossCollisionBlock",  # Parent of FenceBlock, WallBlock, IronBarsBlock
    # "WaterloggedTransparentBlock",  # Parent class
]

# Blocks that need special handling (different canPlaceLiquid logic)
SPECIAL_BLOCKS = {
    "SlabBlock": "state.getValue(SlabBlock.TYPE) != SlabType.DOUBLE",
    "ScaffoldingBlock": "true",  # Always allow
}

# Additional imports needed for specific blocks
EXTRA_IMPORTS = {
    "SlabBlock": [
        "import net.minecraft.world.level.block.state.properties.SlabType;",
    ],
}

MIXIN_TEMPLATE = '''package com.crabmod.hotbath.mixin;

import com.crabmod.hotbath.waterlogging.HotbathWaterloggingHelper;
import net.minecraft.core.BlockPos;
import net.minecraft.tags.FluidTags;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.{block_class};
import net.minecraft.world.level.block.SimpleWaterloggedBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.level.material.Fluids;
{extra_imports}import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Mixin for {block_class} to support hotBath fluid waterlogging.
 * Auto-generated by generate_waterlogging_mixins.py
 * 
 * Priority 500 ensures we run before other mods' mixins.
 */
@Mixin(value = {block_class}.class, priority = 500)
public abstract class {block_class}Mixin extends Block implements SimpleWaterloggedBlock {{

    public {block_class}Mixin(Properties properties) {{
        super(properties);
    }}

    @Inject(method = "canPlaceLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$canPlaceLiquid(BlockGetter level, BlockPos pos, BlockState state, Fluid fluid,
                                         CallbackInfoReturnable<Boolean> cir) {{
        {can_place_check}
        boolean isWaterlogged = state.getValue(BlockStateProperties.WATERLOGGED);
        boolean isWaterTagFluid = fluid.defaultFluidState().is(FluidTags.WATER);
        if (!isWaterlogged && isWaterTagFluid) {{
            cir.setReturnValue(true);
        }}
        {can_place_end}
    }}

    @Inject(method = "placeLiquid", at = @At("HEAD"), cancellable = true)
    private void hotbath$placeLiquid(LevelAccessor level, BlockPos pos, BlockState state, FluidState fluidState,
                                      CallbackInfoReturnable<Boolean> cir) {{
        {place_check}
        if (fluidState.is(FluidTags.WATER) && !state.getValue(BlockStateProperties.WATERLOGGED)) {{
            // DEFENSIVE: Get fresh block state from world to ensure we have the latest
            BlockState currentState = level.getBlockState(pos);
            
            // Verify the block is still the same type and not already waterlogged
            if (!currentState.is(state.getBlock())) {{
                cir.setReturnValue(false);
                return;
            }}
            
            if (currentState.hasProperty(BlockStateProperties.WATERLOGGED) 
                    && currentState.getValue(BlockStateProperties.WATERLOGGED)) {{
                cir.setReturnValue(false);
                return;
            }}
            
            // Store the fluid type for later retrieval
            HotbathWaterloggingHelper.storeFluidType(level, pos, fluidState.getType());
            
            // DEFENSIVE: Create new state from current world state
            BlockState newState = currentState.setValue(BlockStateProperties.WATERLOGGED, true);
            
            // Set the block state with flag 3 (notify clients + neighbors)
            boolean success = level.setBlock(pos, newState, 3);
            
            if (success) {{
                level.scheduleTick(pos, fluidState.getType(), fluidState.getType().getTickDelay(level));
                
                // DEFENSIVE: Verify the block was actually set correctly
                BlockState verifyState = level.getBlockState(pos);
                if (!verifyState.hasProperty(BlockStateProperties.WATERLOGGED) 
                        || !verifyState.getValue(BlockStateProperties.WATERLOGGED)) {{
                    level.setBlock(pos, newState, 2 | 16 | 32 | 64);
                }}
            }} else {{
                HotbathWaterloggingHelper.removeFluidType(level, pos);
            }}
            
            cir.setReturnValue(success);
        }}
        {place_end}
    }}

    @Inject(method = "pickupBlock", at = @At("HEAD"), cancellable = true)
    private void hotbath$pickupBlock(LevelAccessor level, BlockPos pos, BlockState state,
                                      CallbackInfoReturnable<ItemStack> cir) {{
        {pickup_check}
        if (state.getValue(BlockStateProperties.WATERLOGGED)) {{
            Fluid storedFluid = HotbathWaterloggingHelper.getStoredFluidType(level, pos);
            
            if (storedFluid != null && storedFluid != Fluids.WATER && storedFluid != Fluids.EMPTY) {{
                // DEFENSIVE: Get fresh state from world
                BlockState currentState = level.getBlockState(pos);
                if (currentState.hasProperty(BlockStateProperties.WATERLOGGED)) {{
                    level.setBlock(pos, currentState.setValue(BlockStateProperties.WATERLOGGED, false), 3);
                }}
                
                HotbathWaterloggingHelper.removeFluidType(level, pos);
                HotbathWaterloggingHelper.removeFromClientCache(pos);
                
                ItemStack bucket = new ItemStack(storedFluid.getBucket());
                if (!bucket.isEmpty() && bucket.getItem() != Items.AIR) {{
                    cir.setReturnValue(bucket);
                }}
            }}
        }}
        {pickup_end}
    }}
}}
'''

def generate_mixin(block_class: str, output_dir: Path) -> str:
    """Generate a mixin class for the given block class."""
    
    # Check for special handling
    special_check = SPECIAL_BLOCKS.get(block_class)
    
    if special_check:
        can_place_check = f"if ({special_check}) {{"
        can_place_end = "}"
        place_check = f"if ({special_check}) {{"
        place_end = "}"
        pickup_check = f"if ({special_check}) {{"
        pickup_end = "}"
    else:
        can_place_check = ""
        can_place_end = ""
        place_check = ""
        place_end = ""
        pickup_check = ""
        pickup_end = ""
    
    # Get extra imports
    extra_imports = ""
    if block_class in EXTRA_IMPORTS:
        extra_imports = "\n".join(EXTRA_IMPORTS[block_class]) + "\n"
    
    content = MIXIN_TEMPLATE.format(
        block_class=block_class,
        extra_imports=extra_imports,
        can_place_check=can_place_check,
        can_place_end=can_place_end,
        place_check=place_check,
        place_end=place_end,
        pickup_check=pickup_check,
        pickup_end=pickup_end,
    )
    
    # Clean up empty lines for non-special blocks
    if not special_check:
        content = content.replace("        \n", "")
    
    output_file = output_dir / f"{block_class}Mixin.java"
    
    return content, output_file


def generate_mixins_json(blocks: list[str]) -> str:
    """Generate the mixins.json content."""
    # Keep existing mixins that are not auto-generated
    mixin_list = ["FishingHookMixin", "LevelFluidStateMixin"]
    mixin_list.extend([f"{block}Mixin" for block in blocks])
    
    mixins_str = ",\n    ".join([f'"{m}"' for m in mixin_list])
    
    return f'''{{
  "required": true,
  "minVersion": "0.8",
  "package": "com.crabmod.hotbath.mixin",
  "compatibilityLevel": "JAVA_17",
  "refmap": "hotbath.refmap.json",
  "mixins": [
    {mixins_str}
  ],
  "client": ["client.BlockRenderDispatcherMixin"],
  "injectors": {{
    "defaultRequire": 1
  }}
}}
'''


def main():
    # Get the script directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    mixin_dir = project_root / "src" / "main" / "java" / "com" / "crabmod" / "hotbath" / "mixin"
    resources_dir = project_root / "src" / "main" / "resources"
    
    print(f"Generating mixins in: {mixin_dir}")
    
    # Ensure directory exists
    mixin_dir.mkdir(parents=True, exist_ok=True)
    
    generated_files = []
    
    for block_class in WATERLOGGED_BLOCKS:
        content, output_file = generate_mixin(block_class, mixin_dir)
        
        # Only write if file doesn't exist or is different
        if output_file.exists():
            existing = output_file.read_text(encoding='utf-8')
            if existing == content:
                print(f"  Skipped (unchanged): {block_class}Mixin.java")
                generated_files.append(block_class)
                continue
        
        output_file.write_text(content, encoding='utf-8')
        print(f"  Generated: {block_class}Mixin.java")
        generated_files.append(block_class)
    
    # Generate mixins.json
    mixins_json = generate_mixins_json(generated_files)
    mixins_json_file = resources_dir / "hotbath.mixins.json"
    mixins_json_file.write_text(mixins_json, encoding='utf-8')
    print(f"\nUpdated: {mixins_json_file}")
    
    print(f"\n✅ Generated {len(generated_files)} mixin files")
    print("\nNote: Some blocks may need manual adjustments if they have special waterlogging logic.")


if __name__ == "__main__":
    main()
